version: 0.2

phases:
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - coverage run -m unittest tests/unit/*Test.py
      - coverage report -m
# reports:
#   jest_reports:
#     files:
#       - report.xml
#     file-format: JUNITXML
#     base-directory: "./"